x = input("Enter a ajective: ")
z = input("Enter a place name: ")
y = input("Enter another adjective: ")
w = input("Enter a verb: ")
v = input("Enter a adjective again: ")
print()
print(f"Yesterday, I went to {z}.")
print(f"I was {x} to see Bro code there.")
print(f"But I was {y} to {w} there.")
print(f"The prime dinosour was {v} to eat a godzilla.")